name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun index.js

      - name: Create Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: website
          path: ./dist/

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: website